[env:esp32]
platform = espressif32@6.6.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  yoursunny/WifiEspNow @ ^0.0.20230713
  links2004/WebSockets @ ^2.4.1

[env:esp32s3]
platform = espressif32@6.6.0
board = lolin_s3_mini
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  yoursunny/WifiEspNow @ ^0.0.20230713
  links2004/WebSockets @ ^2.4.1
